apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gladia-eu-200

generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled

configMapGenerator:
  - name: app-values
    files:
      - values.yaml=values/values.yaml
  - name: app-values-blue
    files:
      - values.yaml=values/values-blue.yaml
  - name: app-values-green
    files:
      - values.yaml=values/values-green.yaml
