apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: demo-app-gladia-eu-200-blue
  namespace: flux
  labels:
    app.kubernetes.io/name: app
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "10m"
spec:
  type: Static
  defaultValues:
    cluster: gladia-eu-200
    environment: staging
    variant: blue
    version: ">=0.0.0-0"
---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: demo-app-gladia-eu-200-green
  namespace: flux
  labels:
    app.kubernetes.io/name: app
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "10m"
spec:
  type: Static
  defaultValues:
    cluster: gladia-eu-200
    environment: staging
    variant: green
    version: ">=0.0.0-0"
