#!/usr/bin/env bash

#MISE description="Template Helm chart (alias: h:lint)"
#MISE alias=['h:template']
#MISE dir="{{ cwd }}"
#MISE quiet=true

#USAGE arg "<chart>" default="." help="Chart name"
#USAGE flag "-f --values <path>" env="HELM_VALUES" default="values-local.yaml" help="Values file"
#USAGE flag "--debug" default=#false help="Enable Debug mode"
#USAGE flag "-x" default=#false help="Enable Shell Debug mode"

set -euo pipefail

[[ "$usage_x" == "true" ]] && set -x

HELM_ARGS=""

if [[ -s "${usage_values}" ]]; then
  HELM_ARGS+=" --values=${usage_values}"
fi

helm template --debug=${usage_debug} ${HELM_ARGS} ${usage_chart}
