#!/usr/bin/env bash

#MISE description="Upgrade Helm release from local helm chart (alias: h:up)"
#MISE alias=['h:upgrade', 'h:up']
#MISE dir="{{ cwd }}"
#MISE quiet=true

#USAGE arg "<release>" env="HELM_RELEASE" help="Release name"
#USAGE arg "<chart>" default="." help="Chart"
#USAGE flag "--kube-context <kube_context>" env="HELM_KUBE_CONTEXT" default="" help="Kube context"
#USAGE flag "-n --namespace <namespace>" env="HELM_NAMESPACE" default="" help="Cluster Namespace"
#USAGE flag "-f --values <path>" env="HELM_VALUES" default="values-local.yaml" help="Values file"
#USAGE flag "-v --version <version>" env="HELM_CHART_VERSION" default="" help="Chart version"
#USAGE flag "--timeout <time>" env="HELM_TIMEOUT" default="300s" help="Time to wait for any individual Kubernetes operatione (default: 300s)"
#USAGE flag "--devel" default=#true help="Use development versions, too"
#USAGE flag "--take-ownership" default=#false help="If set, upgrade will ignore the check for helm annotations and take ownership"
#USAGE flag "-x" default=#false help="Enable Debug mode"

set -euo pipefail

[[ "$usage_x" == "true" ]] && set -x

HELM_ARGS=""

if [[ -n "${usage_kube_context}" ]]; then
  HELM_ARGS+=" --kube-context=${usage_kube_context}"
fi

if [[ -s "${usage_values}" ]]; then
  HELM_ARGS+=" --values=${usage_values}"
fi

if [[ -n "${usage_version}" ]]; then
  HELM_ARGS+=" --version=${usage_version}"
fi

helm upgrade --install \
  --rollback-on-failure \
  --history-max=3 \
  --create-namespace \
  --devel="${usage_devel}" \
  --timeout=${usage_timeout} \
  --take-ownership="${usage_take_ownership}" \
  --namespace=${usage_namespace} \
  ${HELM_ARGS} ${usage_release} ${usage_chart}
