apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: demo-app
  namespace: flux
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "10m"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: app
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app.kubernetes.io/name: app
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: demo
        namespace: << inputs.cluster >>
      spec:
        type: "oci"
        interval: 1m
        url: oci://ghcr.io/opopops/demo/helm
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      metadata:
        name: app-<< inputs.variant >>
        namespace: << inputs.cluster >>
      spec:
        interval: 1m
        chart: app
        ignoreMissingValuesFiles: false
        valuesFiles:
          - values.yaml
          # - values-<< inputs.environment >>.yaml
        reconcileStrategy: ChartVersion
        sourceRef:
          kind: HelmRepository
          name: demo
        version: "<< inputs.version | quote >>"
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: app-<< inputs.variant >>
        namespace: << inputs.cluster >>
      spec:
        kubeConfig:
          secretRef:
            name: << inputs.cluster >>-kubeconfig
        interval: 30m
        releaseName: demo-app-<< inputs.variant >>
        storageNamespace: default
        targetNamespace: default
        install:
          createNamespace: true
          remediation:
            retries: 3
        upgrade:
          remediation:
            retries: 3
        test:
          enable: false
        driftDetection:
          mode: enabled
          ignore:
            - paths: ["/spec/replicas"]
              target:
                kind: Deployment
        chartRef:
          kind: HelmChart
          name: app-<< inputs.variant >>
        valuesFrom:
          - kind: ConfigMap
            name: demo-app-values
          - kind: ConfigMap
            name: demo-app-values-<< inputs.variant >>
            optional: true
